language: ruby
sudo: false
gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_2.gemfile
rvm:
  - '1.8.7'
branches:
  only:
    - master
addons:
  code_climate:
    repo_token: 69a23bee43b8c53271b1a6fbe18b6167de91a06d66ab19908dd52f73158ab71b
matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx